# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from application_table import Table, LocationException
from intermediate_table import InterTable


class Ui_MainWindow(object):
    """
       This class builds a Graphical user interface. It does so by using two methods;
       One for seting up the GUI and another one for doing the naming of the text found
       on the GUI components
    """
    def setupUi(self, MainWindow):
        """
        Initializes and define the components of the GUI.
        Setting up positions, locations, creation of objects, naming them.
        Calling the retranslateUi method to set the text of the objects.
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_operators = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_operators.setGeometry(QtCore.QRect(10, 30, 161, 321))
        self.groupBox_operators.setObjectName("groupBox_operators")
        self.tabWidget_operators = QtWidgets.QTabWidget(self.groupBox_operators)
        self.tabWidget_operators.setGeometry(QtCore.QRect(10, 20, 131, 291))
        self.tabWidget_operators.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_operators.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_operators.setObjectName("tabWidget_operators")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.radioButton_add = QtWidgets.QRadioButton(self.tab)
        self.radioButton_add.setGeometry(QtCore.QRect(10, 20, 61, 19))
        self.radioButton_add.setObjectName("radioButton_add")
        self.radioButton_substract = QtWidgets.QRadioButton(self.tab)
        self.radioButton_substract.setGeometry(QtCore.QRect(10, 50, 81, 19))
        self.radioButton_substract.setObjectName("radioButton_substract")
        self.radioButton_multiply = QtWidgets.QRadioButton(self.tab)
        self.radioButton_multiply.setGeometry(QtCore.QRect(10, 80, 71, 19))
        self.radioButton_multiply.setObjectName("radioButton_multiply")
        self.radioButton_divide = QtWidgets.QRadioButton(self.tab)
        self.radioButton_divide.setGeometry(QtCore.QRect(10, 110, 61, 19))
        self.radioButton_divide.setObjectName("radioButton_divide")
        self.tabWidget_operators.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.radioButton_comp = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_comp.setGeometry(QtCore.QRect(0, 20, 100, 19))
        self.radioButton_comp.setObjectName("radioButton_comp")
        self.radioButton_subs = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_subs.setGeometry(QtCore.QRect(0, 60, 100, 19))
        self.radioButton_subs.setObjectName("radioButton_subs")
        self.tabWidget_operators.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.radioButton_cos = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_cos.setGeometry(QtCore.QRect(10, 20, 51, 19))
        self.radioButton_cos.setObjectName("radioButton_cos")
        self.radioButton_sin = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_sin.setGeometry(QtCore.QRect(10, 60, 51, 19))
        self.radioButton_sin.setObjectName("radioButton_sin")
        self.radioButton_tan = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_tan.setGeometry(QtCore.QRect(10, 88, 51, 31))
        self.radioButton_tan.setObjectName("radioButton_tan")
        self.tabWidget_operators.addTab(self.tab_3, "")

        # This adds all our radio buttons into a single button group
        self.button_group = QtWidgets.QButtonGroup()
        self.button_group.addButton(self.radioButton_add)
        self.button_group.addButton(self.radioButton_substract)
        self.button_group.addButton(self.radioButton_multiply)
        self.button_group.addButton(self.radioButton_divide)
        self.button_group.addButton(self.radioButton_comp)
        self.button_group.addButton(self.radioButton_subs)
        self.button_group.addButton(self.radioButton_cos)
        self.button_group.addButton(self.radioButton_sin)
        self.button_group.addButton(self.radioButton_tan)

        self.groupBox_appfunc = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_appfunc.setGeometry(QtCore.QRect(180, 30, 591, 321))
        self.groupBox_appfunc.setObjectName("groupBox_appfunc")
        self.tableWidget_func = Table(self.groupBox_appfunc)
        self.tableWidget_func.setGeometry(QtCore.QRect(10, 20, 451, 291))
        self.tableWidget_func.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_func.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_func.setDragEnabled(True)
        self.tableWidget_func.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_func.setAlternatingRowColors(True)
        self.tableWidget_func.setCornerButtonEnabled(True)
        self.tableWidget_func.setRowCount(4)
        self.tableWidget_func.setColumnCount(4)
        self.tableWidget_func.setObjectName("tableWidget_func")
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        self.tableWidget_func.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_func.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_func.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_func.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_func.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_func.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_func.setItem(3, 0, item)
        self.tableWidget_func.horizontalHeader().setDefaultSectionSize(104)
        self.tableWidget_func.horizontalHeader().setMinimumSectionSize(24)
        self.pushButton_delete_row = QtWidgets.QPushButton(self.groupBox_appfunc)
        self.pushButton_delete_row.setGeometry(QtCore.QRect(470, 80, 111, 24))
        self.pushButton_delete_row.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_delete_row.setObjectName("pushButton_delete_row")
        self.pushButton_delete_column = QtWidgets.QPushButton(self.groupBox_appfunc)
        self.pushButton_delete_column.setGeometry(QtCore.QRect(470, 110, 112, 24))
        self.pushButton_delete_column.setObjectName("pushButton_delete_column")
        self.pushButton_delete_cell = QtWidgets.QPushButton(self.groupBox_appfunc)
        self.pushButton_delete_cell.setGeometry(QtCore.QRect(470, 140, 111, 31))
        self.pushButton_delete_cell.setObjectName("pushButton_delete_cell")
        self.groupBox_interResult = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_interResult.setGeometry(QtCore.QRect(10, 350, 511, 221))
        self.groupBox_interResult.setObjectName("groupBox_interResult")
        self.tableWidget_inter = InterTable(self.groupBox_interResult)
        self.tableWidget_inter.setGeometry(QtCore.QRect(10, 20, 461, 192))
        self.tableWidget_inter.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_inter.setDragEnabled(True)
        self.tableWidget_inter.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget_inter.setRowCount(6)
        self.tableWidget_inter.setColumnCount(6)
        self.tableWidget_inter.setObjectName("tableWidget_inter")
        self.groupBox_createfunconst = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_createfunconst.setGeometry(QtCore.QRect(520, 350, 251, 221))
        self.groupBox_createfunconst.setObjectName("groupBox_createfunconst")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_createfunconst)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 215, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_save)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_clear)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/filenew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon1)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon2)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon3)
        self.action_Save.setObjectName("action_Save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/filequit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon4)
        self.action_Exit.setObjectName("action_Exit")
        self.actionAbout_Software = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/editzoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Software.setIcon(icon5)
        self.actionAbout_Software.setObjectName("actionAbout_Software")
        self.action_SaveAs = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/filesaveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SaveAs.setIcon(icon6)
        self.action_SaveAs.setObjectName("action_SaveAs")
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_SaveAs)
        self.menuFile.addAction(self.action_Exit)
        self.menuHelp.addAction(self.actionAbout_Software)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_operators.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_operators.setTitle(_translate("MainWindow", "Operators"))
        self.radioButton_add.setText(_translate("MainWindow", "Add"))
        self.radioButton_substract.setText(_translate("MainWindow", "substract"))
        self.radioButton_multiply.setText(_translate("MainWindow", "Multiply"))
        self.radioButton_divide.setText(_translate("MainWindow", "Divide"))
        self.tabWidget_operators.setTabText(self.tabWidget_operators.indexOf(self.tab), _translate("MainWindow", "Artihmetic"))
        self.radioButton_comp.setText(_translate("MainWindow", "Composition"))
        self.radioButton_subs.setText(_translate("MainWindow", "Substitution"))
        self.tabWidget_operators.setTabText(self.tabWidget_operators.indexOf(self.tab_2), _translate("MainWindow", "Algebraic"))
        self.radioButton_cos.setText(_translate("MainWindow", "cos"))
        self.radioButton_sin.setText(_translate("MainWindow", "sin"))
        self.radioButton_tan.setText(_translate("MainWindow", "tan"))
        self.tabWidget_operators.setTabText(self.tabWidget_operators.indexOf(self.tab_3), _translate("MainWindow", "Trigonometric"))
        self.groupBox_appfunc.setTitle(_translate("MainWindow", "Application of functions"))
        __sortingEnabled = self.tableWidget_func.isSortingEnabled()
        self.tableWidget_func.setSortingEnabled(False)
        item = self.tableWidget_func.item(0, 1)
        item.setText(_translate("MainWindow", "g(y1,y2)"))
        item = self.tableWidget_func.item(0, 2)
        item.setText(_translate("MainWindow", "h(y1)"))
        item = self.tableWidget_func.item(0, 3)
        item.setText(_translate("MainWindow", "n"))
        item = self.tableWidget_func.item(1, 0)
        item.setText(_translate("MainWindow", "f(x1,x2)"))
        item = self.tableWidget_func.item(2, 0)
        item.setText(_translate("MainWindow", "k(x1)"))
        item = self.tableWidget_func.item(3, 0)
        item.setText(_translate("MainWindow", "m"))
        self.tableWidget_func.setSortingEnabled(__sortingEnabled)
        self.pushButton_delete_row.setText(_translate("MainWindow", "Delete row"))
        self.pushButton_delete_row.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.pushButton_delete_column.setText(_translate("MainWindow", "Delete column"))
        self.pushButton_delete_column.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_delete_cell.setText(_translate("MainWindow", "Delete cell"))
        self.pushButton_delete_cell.setShortcut(_translate("MainWindow", "Del"))
        self.groupBox_interResult.setTitle(_translate("MainWindow", "Intermediate results"))
        self.groupBox_createfunconst.setTitle(_translate("MainWindow", "Create Function/Constant"))
        self.label_10.setText(_translate("MainWindow", "Type"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Constant"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Function"))
        self.label_6.setText(_translate("MainWindow", "Number of args"))
        self.label_8.setText(_translate("MainWindow", "Section"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Vertical"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Horizontal"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.label_5.setText(_translate("MainWindow", "Input Name"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_New.setToolTip(_translate("MainWindow", "Create a grid data file"))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout_Software.setText(_translate("MainWindow", "About Software"))
        self.action_SaveAs.setText(_translate("MainWindow", "&SaveAs"))

import resources_rc             # importing all the resources used
